# Generated by Django 5.2.7 on 2026-01-31 23:43

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=20, unique=True, verbose_name='CNPJ')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('nome_contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato')),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone do Contato')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Condutores',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('laboratorio', models.CharField(max_length=200, verbose_name='Laboratório')),
                ('codigo_controle', models.CharField(blank=True, max_length=20, unique=True, unique_for_date='data_criacao', verbose_name='Cód. Controle')),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('tipo', models.CharField(choices=[('PRINCIPAL', 'Veículo Principal (Cavalo/Truck)'), ('CARRETA', 'Carreta/Reboque')], default='PRINCIPAL', max_length=20)),
                ('propriedade', models.CharField(choices=[('FROTA', 'Frota Própria'), ('AGREGADO', 'Agregado'), ('TERCEIRO', 'Terceiro')], default='FROTA', max_length=20)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nivel_acesso', models.CharField(choices=[('MOBILE', 'App Mobile (Operacional)'), ('FULL', 'Web Completo (Gestor)')], default='MOBILE', max_length=10)),
                ('local_atuacao', models.CharField(blank=True, help_text='Filial ou região de atuação', max_length=100, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Avaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_fiscal', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('EM_ABERTO', 'Em Aberto'), ('DECISAO', 'Em Decisão'), ('AGUARDANDO_DEVOLUCAO', 'Aguardando Devolução'), ('EM_ROTA_DEVOLUCAO', 'Em Rota de Devolução'), ('FINALIZADA', 'Finalizada')], default='EM_ABERTO', max_length=30)),
                ('tipo_finalizacao', models.CharField(blank=True, choices=[('ACEITE', 'Aceita pelo Cliente'), ('DEVOLUCAO_CONCLUIDA', 'Devolução Concluída')], max_length=30, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_decisao', models.DateTimeField(blank=True, null=True)),
                ('data_inicio_devolucao', models.DateTimeField(blank=True, null=True)),
                ('data_finalizacao', models.DateTimeField(blank=True, null=True)),
                ('nf_devolucao', models.CharField(blank=True, max_length=50, null=True)),
                ('local_atuacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Local de Atuação')),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avarias_criadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_avarias.cliente')),
                ('motorista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_avarias.condutor')),
                ('motorista_devolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avarias_devolucao', to='app_avarias.condutor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_avarias.produto')),
                ('veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_avarias.veiculo')),
                ('veiculo_carreta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avarias_carreta', to='app_avarias.veiculo', verbose_name='Carreta (Opcional)')),
                ('veiculo_devolucao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avarias_devolucao', to='app_avarias.veiculo')),
            ],
        ),
        migrations.CreateModel(
            name='AvariaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.ImageField(upload_to='avarias_fotos/%Y/%m/%d/')),
                ('data_upload', models.DateTimeField(auto_now_add=True)),
                ('avaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app_avarias.avaria')),
            ],
        ),
    ]
