# Generated by Django 5.2.7 on 2026-01-31 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avarias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='valor_nf',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da NF'),
        ),
    ]
