# Generated by Django 5.2.7 on 2026-02-01 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avarias', '0002_avaria_valor_nf'),
    ]

    operations = [
        migrations.AddField(
            model_name='avariafoto',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_enviadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
