# Generated by Django 6.0.1 on 2026-02-01 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_avarias', '0002_add_veiculo_devolucao_carreta'),
        ('app_avarias', '0003_avariafoto_criado_por'),
    ]

    operations = [
    ]
