# Generated by Django 5.2.7 on 2026-02-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avarias', '0004_merge_20260131_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='responsavel_prejuizo',
            field=models.CharField(blank=True, choices=[('TRANSBIRDAY', 'Transbirday'), ('CLIENTE', 'Cliente')], max_length=20, null=True, verbose_name='Responsável pelo Prejuízo'),
        ),
    ]
