# Generated by Django 5.2.7 on 2026-02-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avarias', '0005_avaria_responsavel_prejuizo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaria',
            name='responsavel_prejuizo',
            field=models.CharField(blank=True, choices=[('TRANSBIRDAY', 'Transbirday'), ('CLIENTE', 'Cliente'), ('TRANSPORTADORA_TERCEIRA', 'Transportadora Terceira')], max_length=50, null=True, verbose_name='Responsável pelo Prejuízo'),
        ),
    ]
