# Generated by Django 6.0.1 on 2026-02-06 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avarias', '0006_alter_avaria_responsavel_prejuizo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaria',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_avarias.produto'),
        ),
        migrations.AlterField(
            model_name='avaria',
            name='quantidade',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='AvariaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('lote', models.CharField(blank=True, max_length=50, null=True)),
                ('avaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='app_avarias.avaria')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_avarias.produto')),
            ],
        ),
    ]
