# Generated by Django 6.0.1 on 2026-02-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avarias', '0007_alter_avaria_produto_alter_avaria_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='transportadora_cnpj',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ Transportadora'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='transportadora_nome',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Transportadora (Parceiro)'),
        ),
    ]
