# Generated by Django 5.2.7 on 2026-02-11 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avarias', '0008_veiculo_transportadora_cnpj_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDistribuicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do CD')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=2, null=True)),
                ('responsavel', models.CharField(blank=True, max_length=200, null=True, verbose_name='Responsável')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Centro de Distribuição',
                'verbose_name_plural': 'Centros de Distribuição',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='avaria',
            name='cd_armazenagem_reversa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_avarias.centrodistribuicao', verbose_name='CD de Armazenagem (Logística Reversa)'),
        ),
    ]
