# Generated by Django 5.2.7 on 2026-02-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avarias', '0009_centrodistribuicao_avaria_cd_armazenagem_reversa'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaria',
            name='acao',
            field=models.CharField(blank=True, choices=[('ACEITAR', 'Aceitar (Finalizar)'), ('DEVOLVER', 'Iniciar Devolução')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='avaria',
            name='horas_retencao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Horas de Retenção'),
        ),
        migrations.AddField(
            model_name='avaria',
            name='nf_retida_conferencia',
            field=models.CharField(choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=3),
        ),
    ]
